config/routes.rb
Rails.application.routes.draw do
    #User home
    get 'dashboard', to: 'home#index'

    #Projects
    get 'project/:project_id/delete', to: 'project#confirm_destroy', as: 'delete_project'
    get 'project/:project_id/add', to: 'project#add_user', as: 'add_user'
    get '/stats', to: 'home#stats'
    post 'project/:project_id/add', to: 'project#add'
    resources :project, except: [:index,], controller: :project do

        #tasks
        get 'task/:task_id/delete', to: 'task#confirm_destroy', as: 'delete_task'
        resources :task, except: [:index], controller: :task, param: :task_id

    end

    #Sign in/up
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
    devise_scope :user do
        root to: "devise/sessions#new"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, except: :stats

    def index
        @user = current_user
        @projects = @user.projects

        render layout: 'main'
    end

    def stats
        @users = User.most_recent(5)
        @tags = Tag.most_recent(5)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :js do %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<% end %>

<% content_for :button do %>
    <div class="button" data-link="<%= new_project_path %>">
        <i class="fas fa-plus"></i>
    </div>
<% end %>

<% if @projects.length != 0  %>

    <div class="grid-center fill-x">
        <div style="display: flex; grid-auto-flow: column;">
            <div class="tag-container">
                <span class="title">Projects</span>
                <div class="task-container">
                    <% @projects.each do |p| %>
                        <a href="project/<%= p.id %>" class="task"><%= p.name %></a>
                    <% end %>
                </div>
            </div>
            <div class="tag-container">
                <span class="title">Recent Tasks</span>
                <div id="recent-tasks" class="task-container">
                    <% task = @user.latest_tasks(10) %>
                    <% task.each do |t| %>
                        <a href="<%= project_path(t.project) %>" class="task"><%= "#{t.project.name} - #{t.title}" %></a>
                    <% end %>
                    <% unless task.length > 0 %>
                        <span style="text-align: center; color: gray">Looks like no tasks have been assigned to you yet!</span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

<% else %>

    <div class="grid-center fill">
        <div style="text-align: center; color: gray">
            <span>Looks like there's nothing here yet.</span><br>
            <span>Try adding a project above!</span>
        </div>
    </div>

<% end %>

app/views/home/stats.html.erb
<h1>Latest Users</h1>
<ul>
    <% @users.each do |user| %>
        <span><%= user.full_name %></span><br>
    <% end %>
</ul>

<h1>Latest Tags</h1>
<ul>
    <% @tags.each do |tag| %>
        <span><%= tag.name %></span><br>
    <% end %>
</ul>