config/routes.rb
Rails.application.routes.draw do
    #User home
    get 'dashboard', to: 'home#index'

    #Projects
    get 'project/:project_id/delete', to: 'project#confirm_destroy', as: 'delete_project'
    get 'project/:project_id/add', to: 'project#add_user', as: 'add_user'
    get '/stats', to: 'home#stats'
    post 'project/:project_id/add', to: 'project#add'
    resources :project, except: [:index,], controller: :project do

        #tasks
        get 'task/:task_id/delete', to: 'task#confirm_destroy', as: 'delete_task'
        resources :task, except: [:index], controller: :task, param: :task_id

    end

    #Sign in/up
    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
    devise_scope :user do
        root to: "devise/sessions#new"
    end
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :presence => true

    has_and_belongs_to_many :users
    has_many :tasks
    has_many :tags, -> { distinct }, through: :tasks

    def self.assign_and_create(params, user)
        project = Project.create(params)
        project.users << user
        project
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    before_action :authenticate_user!
    before_action :validate_owner, except: [:new, :create]
    layout 'main'

    def show
        @tasks = @project.tasks
        @tags = @project.tags
        @task = Task.new
    end

    def new
        @user = current_user
        @project = Project.new
        @errors = @project.errors
    end

    def create
        @user = current_user
        @project = Project.assign_and_create(project_params, @user)
        validate :new
    end

    def update
        @project.update(project_params)
        if @project.valid?
            @project.save
            render json: {success: true}
        else
            @errors = @project.errors.full_messages
            render json: {success: false, error: @errors}
        end
    end

    def add
        user = User.find_by(email: add_params[:email])
        unless user.nil?
            @project.users << user
            @project.save
            render json: {success: true}
        else
            @errors = ["User not found!"]
            render json: {success: false, error: @errors}
        end
    end

    def users
        users = @project.users.map do |user|
            { id: user.id, name: user.full_id }
        end
        render json: users
    end

    # noinspection RubyArgCount
    def destroy
        @project.users.destroy(@user)
        if @project.users.empty?
            @project.tasks.each do |task|
                task.destroy
            end
            @project.destroy
        end
        redirect_to(dashboard_path)
    end

    private
    def validate(error)
        if @project.valid?
            @project.save
            redirect_to( project_path(@project) )
        else
            @errors = @project.errors.full_messages
            render error
        end
    end

    def project_params
        params.require(:project).permit(:name)
    end

    def add_params
        params.require(:add).permit(:email)
    end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/_add_user.html.erb
<div id="add-user" class="popup invisible">
    <div class="popup-menu">
        <h2>Add User</h2>
        <form id="add_user" class="form" action="javascript:addUser()" accept-charset="UTF-8" method="post">

            <div class="error_display invisible-all">
                <h2><span class="error_number"></span> <span class="error_word"></span> are preventing the user from
                    being added!</h2>
                <ul class="errors">
                </ul>
            </div>

            <div class="field">
                <label for="add_email">Email</label>
                <input autofocus="autofocus" type="email" name="add[email]" id="add_email" />
            </div>

            <div class="actions">
                <input type="submit" name="commit" value="Invite" data-disable-with="Invite" />
            </div>
        </form>
    </div>
</div>

app/views/project/_breadcrumbs.html.erb
<% content_for :breadcrumbs do %>
<span>:</span><a href="<%= project_path(@project) %>"><%= truncate(@project.name, length: 25) %></a>
<% end %>

app/views/project/_delete_project.html.erb
<div id="delete-project" class="popup invisible">
    <div class="popup-menu">
        <div class="form">
            <h2>Are you sure you want to destroy this project?</h2>
            <div class="destroy-buttons">
                <%= link_to 'Destroy', project_path(@project), data: {:confirm => 'Are you sure?'}, :method => :delete %>
            </div>
        </div>
    </div>
</div>

app/views/project/_edit_project.html.erb
<div id="edit-project" class="popup invisible">
    <div class="popup-menu">
        <h2>Edit Project</h2>
        <form class="form" id="edit_project" action="javascript:editProject()" accept-charset="UTF-8">

            <div class="error_display invisible-all">
                <h2><span class="error_number"></span> <span class="error_word"></span> are preventing the project from being edited!</h2>
                <ul class="errors">
                </ul>
            </div>

            <input type="hidden" name="task[project]" id="task_project" value="<%= @project.id %>" />

            <div class="field">
                <label for="project_name">Name</label>
                <input autofocus="autofocus" type="text" value="Test" name="project[name]" id="project_name" />
            </div>

            <div class="actions">
                <input type="submit" name="commit" value="Create" />
            </div>
        </form>
    </div>
</div>

app/views/project/_new_task.html.erb
<div id="new-task" class="popup invisible">
    <div class="popup-menu">
        <h2>New Task</h2>
        <form class="form" id="new_task" action="javascript:newTask()" accept-charset="UTF-8">

            <div class="error_display invisible-all">
                <h2><span class="error_number"></span> <span class="error_word"></span> are preventing the task from being created!</h2>
                <ul class="errors">
                </ul>
            </div>

            <input type="hidden" name="task[project]" id="task_project" value="<%= @project.id %>" />

            <div class="field">
                <label for="task_title">Title</label>
                <input autofocus="autofocus" type="text" name="task[title]" id="task_title" />
            </div>

            <div class="field">
                <label for="task_description">Description</label>
                <textarea name="task[description]" id="task_description"></textarea>
            </div>

            <div class="field" id="user_field">
                <label for="task_users">Users</label>
                <select id="task_users" class="select" name="task[users][]" multiple="multiple">
                </select>
            </div>

            <div class="field">
                <label for="task_tag_name">Tag</label>
                <input type="text" name="task[tag_name]" id="task_tag_name" list="tag-list"/>
            </div>

            <div class="actions">
                <input type="submit" name="commit" value="Create" id="task_create" />
            </div>
        </form>
    </div>
</div>

app/views/project/new.html.erb
<div class="grid-center fill-x">
    <div class="grid-center form-container">
        <h2>New Project</h2>
        <%= form_for @project, url: project_index_path, :html => {:class => 'form'} do |f| %>

            <%= render partial: 'layouts/error' %>

            <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true %>
            </div>

            <div class="actions">
                <%= f.submit "Create" %>
            </div>
        <% end %>
    </div>
</div>

app/views/project/show.html.erb
<%=	render partial: 'breadcrumbs' %>

<% content_for :js do %>
    <%= javascript_include_tag 'project', 'data-turbolinks-track': 'reload' %>
<% end %>

<% content_for :button do %>
    <div class="button" data-target="new-task" data-function="resetNewTask">
        <i class="fas fa-plus"></i>
    </div>
    <div class="button" data-target="add-user">
        <i class="fas fa-user-plus"></i>
    </div>
    <div class="button" data-target="edit-project">
        <i class="fas fa-pencil-alt"></i>
    </div>
    <div class="button" data-target="delete-project">
        <i class="fas fa-trash"></i>
    </div>
<% end %>

<div id="tasks" class="hidden" style="display: flex; grid-auto-flow: column;">
</div>

<div id="welcome" class="grid-center fill hidden">
    <div style="text-align: center; color: gray">
        <span>Looks like there's nothing here yet.</span><br>
        <span>Try adding a task above!</span>
    </div>
</div>

<div id="dimmer" class="invisible"></div>

<%= render partial: 'new_task' %>
<%= render partial: 'edit_project' %>
<%= render partial: 'delete_project' %>
<%= render partial: 'add_user' %>

<div id="view-task" class="popup">
    <div class="popup-menu"></div>
</div>

<datalist id="tags">
</datalist>